package reporting;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfDocument;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import database.DALFactory;
import lombok.Setter;
import models.ImageModel;
import models.PhotographerModel;

import javax.print.Doc;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;

public class PDFMaker {
    @Setter
    private ImageModel img;
    @Setter
    private String tag;
    private Document pdf;
    private PdfWriter writer;
    private DALFactory dal = new DALFactory();


    public void tagProduce() {
        var imgDal = dal.getImageDAL(1);
        var imgs = imgDal.getAllImages();

        Map<String, Integer> tags = new HashMap<>();

        for (var img : imgs) {
            String keyword = img.getKeywords();
            int count = tags.getOrDefault(keyword, 0);
            tags.put(keyword, count + 1);
        }

        try {
            makeListPdf(tags);
        }
        catch (FileNotFoundException | DocumentException e) {
            e.printStackTrace();
        }

    }

    private void makeListPdf (Map<String, Integer> keywords) throws FileNotFoundException, DocumentException{
        pdf = new Document();

        writer = PdfWriter.getInstance(pdf, new FileOutputStream( "/home/mathias/Dropbox/FH/sem_4/SWE/swei/reports/tags.pdf"));

        pdf.open();

        pdf.addCreator("Generated by PicDB(c)");

        PdfPTable tagsTable = new PdfPTable(2);
        tagsTable.setSpacingAfter(10.0f);

        PdfPCell tags = new PdfPCell(new Paragraph("Tags"));
        tags.setColspan(3);
        tagsTable.addCell(tags);

        for (var keyword : keywords.entrySet()) {
            tagsTable.addCell(keyword.getKey());
            tagsTable.addCell(String.valueOf(keyword.getValue()));
        }

        pdf.add(tagsTable);

        pdf.close();
    }

    public void imageProduce() {
        try {
            if(!preparePDF()) {
                return;
            }
            addImages();
        } catch (DocumentException | IOException e) {
            e.printStackTrace();
        }


    }

    private boolean preparePDF() throws DocumentException, IOException {

        pdf = new Document();

        writer = PdfWriter.getInstance(pdf, new FileOutputStream("/home/mathias/Dropbox/FH/sem_4/SWE/swei/reports/tags" + img.getTitle() + ".pdf"));

        pdf.open();

        pdf.addCreator("Generated by PicDB(c)");

        return true;
    }

    private boolean addImages() throws DocumentException, IOException {

        pdf.addHeader("Picture", img.getTitle());

        addImage(img);
        addExif(img);
        addIptc(img);
        addPhotographer(img);

        pdf.close();
        return true;
    }

    private void addImage(ImageModel img) throws DocumentException, IOException {
        Image image1 = Image.getInstance(img.getPath());
        image1.setAlignment(Element.ALIGN_CENTER);
        image1.setCompressionLevel(1);
        image1.scalePercent(10);

        /*double x = image1.getAbsoluteX();
        double x_factor = x / 450;
        image1.scaleAbsoluteWidth(450);*/

        //image1.scalePercent(1, (float) x_factor);

        pdf.add(image1);
    }

    private void addExif(ImageModel img) throws DocumentException{
        PdfPTable exifTable = new PdfPTable(2);
        exifTable.setSpacingAfter(10.0f);

        PdfPCell exif = new PdfPCell(new Paragraph("EXIF"));
        exif.setColspan(3);
        exifTable.addCell(exif);

        exifTable.addCell("Camera Model");
        exifTable.addCell(img.getModel());

        exifTable.addCell("Aperture");
        exifTable.addCell(img.getAperture());

        exifTable.addCell("Exposure Time");
        exifTable.addCell(img.getExposure());

        exifTable.addCell("ISO");
        exifTable.addCell(String.valueOf(img.getIso()));

        exifTable.addCell("Focal Length");
        exifTable.addCell(img.getFocalLength());

        pdf.add(exifTable);
    }

    private void addIptc(ImageModel img) throws DocumentException {
        PdfPTable iptcTable = new PdfPTable(2);
        iptcTable.setSpacingAfter(10.0f);

        PdfPCell iptc = new PdfPCell(new Paragraph("IPTC"));
        iptc.setColspan(3);
        iptcTable.addCell(iptc);

        iptcTable.addCell("Title");
        iptcTable.addCell(img.getTitle());

        iptcTable.addCell("Keywords");
        iptcTable.addCell(img.getKeywords());

        pdf.add(iptcTable);
    }

    private void addPhotographer(ImageModel img) throws DocumentException{
        PhotographerModel photographer = dal.getPhotographerDAL(1).getPhotographer(img.getPhotographerID());

        if (photographer != null) {
            PdfPTable photographerTable = new PdfPTable(2);
            photographerTable.setSpacingAfter(10.0f);

            PdfPCell photogHeader = new PdfPCell(new Paragraph("Photographer"));
            photogHeader.setColspan(3);
            photographerTable.addCell(photogHeader);

            photographerTable.addCell("Last Name");
            photographerTable.addCell(photographer.getSurName());

            photographerTable.addCell("First Name");
            photographerTable.addCell(photographer.getFirstName());

            photographerTable.addCell("Birthdate");
            photographerTable.addCell(photographer.getBirthDate().toString());

            photographerTable.addCell("Notes");
            photographerTable.addCell(photographer.getNotes());

            pdf.add(photographerTable);
        }
    }
}

